### ISSUE TITLE
Some files won't open from File Browser

### ISSUE THREAD

**Issue by zythra** [usysware/dpack#1]
I have an xml file that I use in many of my projects that is in the "Solution Items" folder.  The file shows up just fine in the File Browser but hitting enter with it selected or double clicking on the file won't open it in the editor.  This was working in VS 2015 (it may have worked in VS 2017, but I skipped 2017).

I'm happy to help test any potential fixes for this.

Currently using VS 2019 with DPack 3.12.4.

**Comment by usysware** [comment]
Could you submit a small test solution that would illustrate the problem please? Thanks.

**Comment by zythra** [comment]
[DPackTest.zip](https://github.com/usysware/dpack/files/3814906/DPackTest.zip)

Sure thing Sergey.  I've attached a small project.  When you open the solution you'll see a "SolutionFolder" in the Solution Explorer that contains a file called test.txt.  If you bring up the DPack File Browser you can see test.txt in the list of files but you are unable to open it from the DPack File Browser.  Double clicking the file or hitting enter with the file selected just closes the file browser without opening the file.

![image](https://user-images.githubusercontent.com/25746301/68306969-b82fe700-0067-11ea-800b-57c5601b1b7c.png)

**Comment by usysware** [comment]
Thanks for the test case. Looks like it's the same issue on VS 2017 as well. Patch should be straightforward. I'm a bit hesitant to spend the resources on older code base and might end up checking that in to the new OS branch only. The downside is that version is not nearly ready for even beta release. I've got Code Browser, File Browser, Misc and Bookmarks feature done so far with a few still missing.

**Comment by zythra** [comment]
Oddly I vaguely remember you fixing this in an older version of VS probably 10 years or so ago, I could be remembering wrong, it just seems familiar.  If you'd like a tester for the new version I'd be happy to help.

**Comment by usysware** [comment]
That's possible. I'm pretty sure it didn't work at first before some had brought it up. It could've been broken in VS 2017 time frame and no one noticed.

Thanks. I'll need to finish some tests before I can make it available unless you need it urgently. And as I said, some features won't be available right away like Solution Browser, Solution Backup and Solution Statistics.

**Comment by zythra** [comment]
Honestly, I rarely use those 3 features, so that wouldn't be a show stopper for me in helping to test.  The features I use the very most are File Browser, Code Browser, and Bookmarks.

**Comment by usysware** [comment]
If you get a chance give it a shot with new DPack Rx and let me know how it works. I did test it with the new version so the issue shouldn't manifest itself anymore. Thanks.

**Comment by zythra** [comment]
Happy to test it.  I'll swap out my extension for the Rx beta in the next day or two and give it a go.

**Comment by usysware** [comment]
Great. Thanks.

I'd suggest disabling DPack first (Extensions->Manage Extensions on VS 2019) and then installing DPack Rx. They really are separate extensions that don't clash other than keyboard shortcuts.

**Comment by zythra** [comment]
Sergey, I've removed the old DPack and installed Rx.  So far everything
I've tried works the way it should, including opening secondary solution
files (the culprit in this ticket).  I've played around with both the code
browser and file browser and both seem to be working great.  The dialog
windows are nice and clean, I see you've added a bit of color to them which
is a nice touch.

I don't typically use the solution statistics or solution backup but I
tried them anyway and noticed they're not currently working.  I assume it's
just that they haven't been ported to this new version yet.

Looking good so far.  Let me know how I can help.

**Comment by usysware** [comment]
Great, thanks for confirming it.

Yeah, both File and Code Browsers have been updated to use built-in VS images, other than for shell menus themselves. So everything looks better and on-par with VS.

Not sure if you've noticed or not but File Browser has a few "shortcut" buttons to Code Browser located to the right of search box. That's an attempt to help those who were relying on Solution Browser feature, which isn't gonna get ported. And yeah, you are correct, Solution Backup and Statistics features haven't been migrated yet.

I'm gonna close this issue shortly. Feel free to submit a new ticket if you come across another issue. Thanks again.
