### ISSUE TITLE
How do you open the File Browser?

### ISSUE THREAD

**Issue by coty-crg** [usysware/dpack#12]
Previous version of dpack was "alt+u" to open it. I cannot for the life of me figure out how to open it, on this version. Could you add a keyboard shortcut list or something somewhere?

**Comment by coty-crg** [comment]
![image](https://user-images.githubusercontent.com/3958573/90984706-8e2eaf00-e52b-11ea-9d6c-1863a52f6d4a.png)

Hm, I've tried changing the default keyboard shortcut from ALT+U to CONTROL+B, and still nothing happens in Visual Studio 2019 when I use it.

**Comment by coty-crg** [comment]
Ahhhh such a weird issue. I closed visual studio and reopened several times (from within Unity..) and it still was broken. 

Then I closed it, and opened it normally (NOT from within Unity) and now it works! Must be something about how Unity triggers opening Visual Studio that somehow breaks dpack's shortcuts?! WTF

**Comment by usysware** [comment]
Hi there. Tbhwy, never used Unity in my life. It could be one of the 2 things - it's either a slightly different environment that it doesn't load extensions correctly, or it has additional internal extensions that remap Alt-U for themselves. I'll check it out if I can get it installed. I'll also look into adding a wiki page with all default shortcut keys. Check out DPack's Tools|Options page to reassign the shortcuts to defaults too, assuming that's even applicable for Unity environment.

**Comment by coty-crg** [comment]
Yeah I'm not sure what the issue is. Unity will just open a .cs file through Visual Studio, as you'd expect. It's not like its really within unity, its just launching the VS process from Unity. 

Weirdly enough, after closing VS and opening from within Unity, now it's working. It must just be some first-time setup that goes wrong with dpack and VS when opening from Unity, not every time. 

I understand this is a really annoying problem to debug haha, thats why I closed the topic.

**Comment by usysware** [comment]
I attempted to use Unity just to run into licensing so I'm gonna have to pass on using Unity. :) You did say "open .cs file through VS" that got me thinking. It could be that Unity launches VS in streamlined mode to facilitate code editing mainly. It *could be* disabling 3rd party extensions to be loaded, which would be mainly for performance reason and would explain that behavior. When DPack's fully loaded 2 things happen - you get a status bar message shown that such and such version is loaded, which is not super reliable as something else might be clearing the status bar. And DPack's log file gets all initialization entries written out. So if you could check if you are seeing entries there when new VS instance launches that would validate my theory. Keep in mind, depending on # of VS instances running you'd need to open right log file. See the same Tools|Options dialog for log folder location.

**Comment by usysware** [comment]
> Previous version of dpack was "alt+u" to open it. I cannot for the life of me figure out how to open it, on this version. Could you add a keyboard shortcut list or something somewhere?

Added:
https://github.com/usysware/dpack/wiki/Commands
