### ISSUE TITLE
Code Browser displays nothing in large scale C++ solution.

### ISSUE THREAD

**Issue by jakesgit** [usysware/dpack#13]
Hi, firstly thanks for the providing this great extension for free. Kudos!

DPack in our large C++ solutions at work fails to show anything when opening any of the Code Browser windows. The windows will open, but return no results. It is always just a blank white window:

![image](https://user-images.githubusercontent.com/28767014/91595092-e108cc00-e95a-11ea-9432-469a71a76776.png)

I would expect to see a match in the scenario pictured above.

It may be worth noting that the file browser works perfectly.

Here is dpack log:
[DPack.log](https://github.com/usysware/dpack/files/5143457/DPack.log)
Project and file names were modified as the company I work for is in sensitive field.

System info:

Windows 10 Pro x64 ver 1903
Visual Studio Pro ver 16.4.5
DPack Rx ver 4.0.0.32 Beta

When I create a small dummy project, the feature works as intended:

![image](https://user-images.githubusercontent.com/28767014/91599656-86716f00-e95e-11ea-8d79-fb9382f4ec5b.png)

Sadly I cannot share the problematic projects as they are not open source.

Please let me know if I can provide any more info. 

Thanks.

**Comment by usysware** [comment]
Hi Jake,

Is there any way you could add that file you're having problems with to a brand new project to see if it's still happening or not? That could be a good started. Unfortunately, C++ is not my area of expertise so I'd need to rely on repro case unfortunately.

I do remember one outstanding issue related to C++ and Visual Studio extensibility, which DPack relies on to discover all the file members. The issue, which is still unresolved, is with nested C++ namespaces. Anything declared within nested C++ namespace isn't gonna be exposed through VS extensibility model and thus won't show up Code Browser. Please confirm if that's applicable.

Thanks.

**Comment by usysware** [comment]
Closing. Feel free to re-open when/if you get more information. Thanks.
