### ISSUE TITLE
Can't get it to run,  there is no instructions. Two api's are depreciated.  No instructions hie to fix? No instructions at all on YouTube?

### ISSUE THREAD

**Issue by joep3joep3** [usysware/dpack#15]
1. Clearly describe the issue you're having.
2. Provide steps to reproduce the behavior.
3. Indicate the expected behavior.
4. Include a test project, if possible.
5. Include screenshots, if applicable.
6. Include DPack's log using Tools|Options -> DPack.
7. Add any other details you think might be helpful.
8. Provide your development environment details:
  a. OS type and version
  b. Visual Studio version from Help|About
  c. DPack version from Help|About
  d. Project language you're working with.
  e. Project type you're working with (Win, Web, .NET Core, etc).

Thanks.

**Comment by usysware** [comment]
There is not much to go on in your submission. Could you expand on that just a little? The instructions you posted there are for you to fill out.

**Comment by joep3joep3** [comment]
Couldn't get it to run. Synchronous loading enabled but still wouldn't run.
Left me without being able to debug my package. Forced me to recover my
code from the ssis package. Uninstalled the addin. Left all my ssis
packages incompatible. Needed to reinstall ssis.

A complete shit show.

**Comment by zythra** [comment]
@joep3joep3 I'm a user just like you so I have no personal bias nor vested interest in DPack other than as a user.  That said, you are being utterly disrespectful toward the developer of DPack.  Nobody forced you to install it.  It's FREE and you installed it of your own free will and choice.  You didn't like it, so move on instead of throwing a tantrum.

**Comment by joep3joep3** [comment]
Ok but think of me when this happens to you. This is an ongoing issue and
the developers are not saying anything about it. Disrespectful,  I lost a
couple of days programming with no warning. They know about this.

**Comment by zythra** [comment]
I've had plenty of tools wreak havoc for me, but software is imperfect and as a developer I am fully aware of that.  I've been using DPack for over 15 years and the developer is fantastic.  The developer owes you nothing.  It's a free tool that nobody is forcing you to use and it is developed and maintained during the developers free time, not as a job.  They can't account for every possible scenario in every users setup.  As a developer you should know that.  As far as having no warning, you chose to install it and you took the risk just like any other user that installs a program.  Move on.  Go purchase ReSharper if you need hand held support, not a tool that the developer graciously offers for free to the thousands that happily use it without issue.

**Comment by usysware** [comment]
> Couldn't get it to run.

Let me refer you again to the 8-point questioner you posted with originally. All those questions would've needed to be answered for me to have any ideas as to what you're talking about.

> Synchronous loading enabled but still wouldn't run.

That's about the only useful information you had provided. Disable synchronous loading it and uninstall the extension.
https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2019#uninstall-or-disable-an-extension

I'm gonna refrain from replying to the rest of your comments. Closing the issue.
