### ISSUE TITLE
DPack menu does not appear at visual studio 2019 after installation

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [usysware/dpack#5]
Hi,

I've installed DPack extension on my VS2019. Though the extension manager shows DPack is installed, I don't see the menu of it at the 'Tools' pop-up menu, as I used to see at VS2017.
Also clicking on Alt+U does not open the 'browse files' dialog. 
So it seems it is does not work well. I tried to uninstall and install, but this did not solve the problem.

Any suggestion is much appreciated.

Thanks.
Eliyahu

**Comment by Eliyahu-Machluf** [comment]
I'm using VS2019 professional, and the extension manager shows Dpack as installed.
![VS_extension_manager](https://user-images.githubusercontent.com/16648676/69914690-6fddcc00-144f-11ea-93ca-d148eec624c7.jpg)

**Comment by usysware** [comment]
Change this setting for DPack to start working:
![Settings](https://user-images.githubusercontent.com/55639583/69914879-1a85c880-1417-11ea-83f8-9a2c59b36453.png)
Next major version of DPack won't require that change anymore.

**Comment by Eliyahu-Machluf** [comment]
Thanks for the quick response.
I tried this and it did not solve the issue.
It caused a new problem, I could not build my project, getting the error: The operation cannot be completed because BeginBuild has not yet been called.

After disabling the DPack extension, the build run OK.

**Comment by usysware** [comment]
DPack doesn't plug into build chain in any way. The problem must be unrelated despite of how it may appear to be. My guess it's some other extension causing that problem. Uninstall DPack, enable the above mentioned setting and see if your problem still persists. Go through your 3rd party extensions in the similar manner 1 by 1 to narrow it down to offending one. Good luck.

**Comment by Eliyahu-Machluf** [comment]
Thanks. Currently I'm busy with some work stuff, so I won't do more tests with DPack now.
Anyway, thanks for your assistance.

**Comment by Eliyahu-Machluf** [comment]
Hi,

Now I had some time to play with vs extensions, and I want to share with you, now I'm using Visual Studio 2019 with DPACK and all works fine :-)
Seems the issue was because I used visual studio blend and not regular visual studio application.
Anyway, now it works fine, and I can enjoy and benefit DPACK.

Thanks for the assistance.

Eliyahu

**Comment by usysware** [comment]
Good deal. I don't Blend myself or target it with DPack. Not sure how or if DPack would even work with it. So I'm not surprised it's not showing up. Thanks for the update.
