### ISSUE TITLE
NullRefException when loading FileBrowser on a solution with an unloaded project

### ISSUE THREAD

**Issue by jpnoir** [usysware/dpack#6]
[NullRefException.txt](https://github.com/usysware/dpack/files/4237459/NullRefException.txt)
[BugRepo.zip](https://github.com/usysware/dpack/files/4237629/BugRepo.zip)

VS2019 v16.4.5
DPack Rx v4.0.0.22

Unzip BugRepo.zip.
Open it in VisualStudio.
Unload the project named "UnusedProject".
Bring up the File Browser (Alt-U).

You should see a null ref exception with a stack trace similar to the one in the attachment, NullRefException.txt

**Comment by usysware** [comment]
Thanks for the report. Reproduced it internally and fixed for the next release, which should happen sometimes over the weekend. Looks like it was a regression type issue.

**Comment by usysware** [comment]
New version is up. Give it a try to see how it works for you. Thanks.

**Comment by jpnoir** [comment]
Yes, The new version is working fine now. Thanks!

**Comment by usysware** [comment]
Great. Thanks for letting me know.
