### ISSUE TITLE
Bookmarks are bound to a specific file

### ISSUE THREAD

**Issue by Fulgan** [usysware/dpack#61]
1. Clearly describe the issue you're having.

The current way the bookmarks work, they are tied to a specific file: it is not possible to go to a bookmark using the keyboard shortcut when the file that contains that bookmark isn't the one focused

3. Provide steps to reproduce the behavior.

Open 2 files
Set a bookmark on first file
Focus the second file
Press the shortcut for navigating to the bookmark -> fail

5. Indicate the expected behavior.

The IDE should focus on the file containing the bookmark and navigate to it

Thank you :)

**Comment by sergey-visual-studio** [comment]
What you describe is intended behavior. Regular bookmarks work within a give file. There is also Global Bookmark sub-feature, which allows one to navigate to that regardless of the currently opened file.
