### ISSUE TITLE
Support Code browsing for Shared project

### ISSUE THREAD

**Issue by dhervieux** [usysware/dpack#8]
Hello,
  I get this message when I try to browse a file in a shared project: Code Browser request cannot be processed

I'm using Visual Studio 2019 with a Winforms project (.NET 4.7.2) but the library contains a Shared project used by our other plateforms.

Regards
![DPackShared](https://user-images.githubusercontent.com/801431/78597032-c81c4480-781a-11ea-8f2e-a00586a5faf9.png)

**Comment by usysware** [comment]
Hi there,

DPack relies on Visual Studio file code model to present all of solution/project/file data. Unfortunately, it appears that shared projects do not expose that file code model, making them inaccessible to DPack. As a confirmation of that notice that C# files in your picture don't have "expand icon" (other than some form you have there), which indicates and confirms that there is no exposed file code model there.

The only option here would be to migrate from file code model to using Roslyn for file processing instead. Unfortunately, Roslyn doesn't support C++ project making it a non-starter for now.

So shared projects will unfortunately remain unsupported for the time being.

Thanks for bringing it up.
